import type { Metadata } from "next";
import {
  Cormorant_Garamond,
  Herr_Von_Muellerhoff,
  Monsieur_La_Doulaise,
} from "next/font/google";
import "./globals.css";

const cormorantGaramond = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  style: ["normal", "italic"],
  variable: "--font-cormorant",
});

const herrVonMuellerhoff = Herr_Von_Muellerhoff({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-herr-von-muellerhoff",
});

const monsieurLaDoulaise = Monsieur_La_Doulaise({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-monsieur-la-doulaise",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cormorantGaramond.variable} ${herrVonMuellerhoff.variable} ${monsieurLaDoulaise.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
